java_binary(
	name = "launcher",
	srcs = ["Launcher.java"],
	main_class = "org.delahoz.Launcher",
	deps = ["//src/java/main/org/delahoz/library_java:library_java"],
	visibility = ["//src/java/main/org/delahoz:__pkg__"],
	)
